name: xelis_dart_sdk
description: Software Development Kit in Dart to build Apps for the XELIS Blockchain.
version: 0.30.6
repository: https://github.com/xelis-project/xelis-dart-sdk

environment:
  sdk: '^3.8.0'

dependencies:
  convert: ^3.1.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  json_rpc_2: ^4.0.0
  jsontool: ^2.1.0
  logging: ^1.3.0
  very_good_analysis: ^10.0.0
  web_socket_client: ^0.2.1

dev_dependencies:
  build_runner: ^2.7.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  lints: ^6.0.0
  test: ^1.26.3
